---List of valid PlayerModelParts. Used within the PlayerAPI.
---@alias PlayerModelParts
---| 'CAPE'
---| 'JACKET'
---| 'LEFT_SLEEVE'
---| 'RIGHT_SLEEVE'
---| 'LEFT_PANTS_LEG'
---| 'RIGHT_PANTS_LEG'
---| 'HAT'
