---List of valid RenderTypes. Used within the Item RenderTask.
---@alias ItemRenderTypes
---| 'NONE'
---| 'THIRD_PERSON_LEFT_HAND'
---| 'THIRD_PERSON_RIGHT_HAND'
---| 'FIRST_PERSON_LEFT_HAND'
---| 'FIRST_PERSON_RIGHT_HAND'
---| 'HEAD'
---| 'GUI'
---| 'GROUND'
---| 'FIXED'
