---@diagnostic disable: duplicate-set-field
---A global API that contains all of the figura Events. Accessed using the name "events".
---@class EventsAPI
---@field ENTITY_INIT Event The ENTITY_INIT event is run once this avatar's entity exists.
---@field TICK Event The TICK event is run every tick in-game if this avatar's entity exists.
---@field WORLD_TICK Event The WORLD_TICK event is run every in-game tick.
---@field RENDER Event The RENDER event is run every frame, before the avatar is rendered. Takes a parameter delta, which is a number from 0 to 1 indicating the proportion of the way the game is between ticks.
---@field POST_RENDER Event The POST_RENDER event runs every frame, after the avatar is rendered. Takes a parameter delta, which is a number from 0 to 1 indicating the proportion of the way the game is between ticks.
---@field WORLD_RENDER Event The WORLD_RENDER event is run every frame, before the world is rendered. Always runs when a world is visible, even when the avatar itself is not, so this runs even in first person. Takes a parameter delta, which is a number from 0 to 1 indicating the proportion of the way the game is between ticks.
---@field POST_WORLD_RENDER Event The POST_WORLD_RENDER event runs every frame, after the world is rendered. Always runs when a world is visible, even when the avatar itself is not, so this runs even in first person. Takes a parameter delta, which is a number from 0 to 1 indicating the proportion of the way the game is between ticks.
---@field CHAT_SEND_MESSAGE Event The CHAT_SEND_MESSAGE event is run every time you send a message in chat. A string parameter is passed in, which contains the message that was sent. The return value is chained to the next events of the same type, whereas NIL cancels the message from being sent and any other value will modify the sent message (if allowed in the settings).
---@field CHAT_RECEIVE_MESSAGE Event The CHAT_RECEIVE_MESSAGE event is run every time a message is received in chat. A string parameter is passed in, which contains the message you received.
---@field SKULL_RENDER Event Called between POST_RENDER and POST_WORLD_RENDER, on every one of your skull blocks placed in the world. The arguments are the tick delta and the position of the skull as a vector.
---@field MOUSE_SCROLL Event The MOUSE_SCROLL event runs every time the mouse is scrolled. Takes a parameter delta, which is the direction of the scroll.
---@field PREVIEW_RENDER Event The PREVIEW_RENDER event runs every frame an avatar preview is being rendered, either be it by the paperdoll, Figura Wardrobe or Inventory.
---@field POST_PREVIEW_RENDER Event The POST_PREVIEW_RENDER event runs every frame, after the avatar preview is being rendered, either be it by the paperdoll, Figura Wardrobe or Inventory.
local EventsAPI={}
